server:
  port: xxxx
spring:
  # 支持 swagger3
  mvc:
    pathmatch:
      matching-strategy: xxx
  mail:
    host: smtp.163.com
    port: 25
    username: xxx
    password: xxx
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.53.236.156:3306/xxxx
    username: xxx
    password: xxxx
  # Redis 配置
  redis:
    database: 1
    host: xxx.xx.xxx.xx
    port: xxx
    timeout: xxx
    password: xxx

  #rabbitMq配置
  rabbitmq:
    host: xxx.xx.xxx.xx
    port: xxx
    username: xxx
    password: xxx
  # Elasticsearch 配置
  # todo 需替换配置，然后取消注释
  #  elasticsearch:
  #    uris: http://localhost:9200
  #    username: root
  #    password: 123456
  # 文件上传
  servlet:
    multipart:
      # 大小限制
      max-file-size: 10MB

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名
      logic-delete-value: 1 # 逻辑已删除值（默认为 1）
      logic-not-delete-value: 0 # 逻辑未删除值（默认为 0）
# 微信相关
wx:
  # 微信公众平台
  # todo 需替换配置
  mp:
    token: xxx
    aesKey: xxx
    appId: xxx
    secret: xxx
    config-storage:
      http-client-type: HttpClient
      key-prefix: wx
      redis:
        host: xxx
        port: xxx
      type: Memory
  # 微信开放平台
  # todo 需替换配置
  open:
    appId: xxx
    appSecret: xxx
# 对象存储
# COS
cos:
  client:
    accessKey: xxx
    secretKey: xxx
    region: xxx
    bucket: xxx
# OSS
alibaba:
  cloud:
    oss:
      endpoint: xxx
      bucket: web-hehe-wocao
      domain: xxx
    access-key: xxx
    secret-key: xxx
# gitee
gitee:
  clientId: xxx
  clientSecret: xxx
  state: GITEE
  redirectUri: xxx
  token:
    url: xxx
  user:
    url: xxx
    prefix: xxx
# github
github:
  clientId: xxx
  clientSecret: xxx
  state: GITHUB
  redirectUri:xxx
  token:
    url: xxx
  user:
    url: xxx
    prefix: xxx